### ISSUE TITLE
Would be possible to use numeric lists similarly as ChatGPT uses them instead of multiple chained `` instances

### ISSUE THREAD

**Issue by byebb** [pionxzh/chatgpt-exporter#13]
Here a detailed example:

![image](https://user-images.githubusercontent.com/4288893/207098262-2ec9a4ee-b5e5-4993-8289-0f1b13f969ac.png)

Exported result:

![image](https://user-images.githubusercontent.com/4288893/207098317-96c1319b-2f99-4c28-8b37-dd6edda65c7e.png)

That'd be amazing!

**Comment by byebb** [comment]
I found an easy possible solution. Simply replace [line 63](https://github.com/pionxzh/chatgpt-exporter/blob/76d408287c8faae57be4a726ca34fdfddf8c537f/packages/userscript/src/template.html#L63) in the template file `template.html` the content:

```css
        p>code::before,
        p>code::after {
            content: "`";
        }
```

with

```css
        p>code::before{
            content: "\a>>> `";
        }

        p>code::after {
            content: "`";
        }
```

then, it already looks quite good:

![image](https://user-images.githubusercontent.com/4288893/208057851-0779fe1d-a315-432d-819d-244517810212.png)


or alternatively:

```css
        p>code::before{
            content: "\a`";
        }
        
        p>code::after {
            content: "`\a";
        }
```

result:

![image](https://user-images.githubusercontent.com/4288893/208057919-ead5e439-53db-4c68-89bb-7991beb02ecf.png)


I prefer the former. While the empty line is especially useful for longer text, instead of simple bullet point lists.
